### ISSUE TITLE
Ccboot check hakkında bir istek

### ISSUE THREAD

**Issue by ActualBury** [lukacci/cpuhunter#1]
cpuhunterw da bir bölüm olsa ve kontrol tuşuna veya adı ne olursa bir tuşa bassak ve program bize "Bu bilgisayar ccboot kullanıyor" veya "Bu bilgisayar ccboot kullanmıyor" gibi bir uyarı verse çok kullanışlı olurdu

**Comment by lukacci** [comment]
Merhaba, talebiniz not edildi ve güncelleme sırasına dahil edildi.
