### ISSUE TITLE
Windows adresi bulunamadi

### ISSUE THREAD

**Issue by xturkhackerx** [lukacci/cpuhunter#3]
Bir bilgisayarda windows adresi bulunamadi  diye hata veriyor ne yapmaliyim ve bazi bilgisayarlarda bios menüsünde sifre var tesekkurler

**Comment by lukacci** [comment]
Bu hata, bilgisayarda Windows yüklü olmadığı ya da bilgisayara takılı disk olmadığı anlamına gelir. Genellikle diskless sistemlerde ortaya çıkan bir hatadır. Cpuhunter harddisk üzerine yüklenir. Şuan için herhangi bir çözüm yok gibi görünüyor farklı bir bilgisayara geçebilirsiniz. Diskless sistemler hakkıda çalışmalarımız devam ediyor herhangi bir gelişme olduğunda programa dahil edilecektir. İlerleyen dönemlerde bu problem mutlaka giderilecektir.

**Comment by xturkhackerx** [comment]
Kucuk bilgisayarlarda oluyor galiba,
1 bilgisayar gunde kac para yapiyor

Am Do., 8. Nov. 2018, 07:20 hat lukacci <notifications@github.com>
geschrieben:

**Comment by xturkhackerx** [comment]
Birde bios sifresi varsa giremeyiz boot menuye

Am Do., 8. Nov. 2018, 09:37 hat Anonymous Earth <atakanumut2003@gmail.com>
geschrieben:

**Comment by lukacci** [comment]
Monero kazançları işlemci gücüne bağlıdır ve bilgisayardan bilgisayara değişir.

**Comment by xturkhackerx** [comment]
Hocam doszalar kopyalanamadı dıyor hıcbır bılgısayarda calısmıyor??
