### ISSUE TITLE
windows adresi bulunamadı cpuhunter

### ISSUE THREAD

**Issue by timurka7484** [lukacci/cpuhunter#6]
diskless sistemlere çözüm lazım acil, ccbootlu pclerde madencilik yapamıyoruz!

**Comment by lukacci** [comment]
Muhtelif sebeplerden dolayı güncellemeler biraz aksamış durumda. 
Yaşanılan problemlerin farkındayız, kısa süre içerisinde yeni düzeltmeler eklenecektir.
